---
apiVersion: v1
kind: PersistentVolume    # 资源类型pv
metadata:
 name: pv-nfs1 # pv的名字
 # 标签
 labels:
   run: nfs1
spec:
  # 运行的访问模式，可以指定多个
  accessModes:
  - ReadWriteMany    # 多节点读写
  # 容量
  capacity:
    storage: 8Gi
  # 回收策略，nfs默认为Retain  
  persistentVolumeReclaimPolicy: Retain  # default 
  # 卷模式，默认为文件系统
  volumeMode: Filesystem  # default 
  nfs:
    server: 192.168.0.105
    path: /data/nfs1
    readOnly: false        # default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: test
spec:
  # 访问模式，需要以pv一致
  accessModes:
  - ReadWriteMany
  # 需要的存储容量，如果大于pv声明的容量则不能匹配
  resources:
    requests:
      storage: 7Gi
  volumeMode: Filesystem   # defailut
  
---
apiVersion: v1
kind: Pod
metadata:
  name:  pvc-nfs-pod
  namespace: test
  labels:
    run: pvc-nfs-pod

spec:
  volumes:
  - name: pvc-nfs
    persistentVolumeClaim:
      claimName: pvc-nfs   # 指定pvc的名字
    
  containers:
  - name: pvc-nfs-pod
    image: centos:7
    command:
    - /bin/sh
    - -c 
    - "for i in {1..1000}; do echo ${i} >> /data/nfs1/exmpale.txt; sleep 1; done"
    
    # 挂载pvc到容器的/data/nfs1目录
    volumeMounts:
    - name: pvc-nfs
      mountPath: /data/nfs1 
 
